name: "[VER:1.1g.20170629-Inventables:]"
board: "[VER:1.1g.20170629-Inventables:]"
verbose_errors: true

stepping:
  engine: RMT
  idle_ms: 20
  pulse_us: 2
axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 20
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 749.000
    homing:
      cycle: 2
      mpos_mm: 1
      positive_direction: false
      pulloff_mm: 2.000
    motor0:
      hard_limits: false
      limit_neg_pin: gpio.17:low:pu
      standard_stepper:
        direction_pin: gpio.14
        step_pin: gpio.12
  y:
    steps_per_mm: 20
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 150.000
    max_travel_mm: 749.000
    homing:
      cycle: 3
      mpos_mm: 1
      positive_direction: false
      pulloff_mm: 2.000
    motor0:
      hard_limits: false
      limit_neg_pin: gpio.4:low:pu
      standard_stepper:
        direction_pin: gpio.15:low
        step_pin: gpio.26
  z:
    steps_per_mm: 188.976
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 100.000
    homing:
      cycle: 1
      mpos_mm: 1
      positive_direction: true
      pulloff_mm: 2.000

    motor0:
      hard_limits: false
      limit_pos_pin: gpio.16:low:pu
      standard_stepper:
        direction_pin: gpio.33:low
        step_pin: gpio.27:low

relay:
  direction_pin: NO_PIN
  output_pin: NO_PIN
  enable_pin: gpio.13
  spinup_ms: 6000
  spindown_ms: 6000
  tool_num: 0
  speed_map: 0=0.000% 0=100.000% 1=100.000%
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

probe:
  pin: gpio.32:low:pu

start:
  must_home: false
  deactivate_parking: false
  enable_parking_override_control: true
  check_limits: false
  startup_line0: $i
  startup_line1: $$
  macros:
  macro0: 
  macro1: 
  macro2:
  macro3: